# Generated by Django 5.0.6 on 2024-05-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="tag",
            field=models.CharField(default="Misc", max_length=50),
            preserve_default=False,
        ),
    ]
