# Generated by Django 5.0.6 on 2024-05-20 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance_tracker", "0002_expense_tag"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="expense",
            name="tag",
            field=models.CharField(
                choices=[
                    ("Food", "Food"),
                    ("Clothing", "Clothing"),
                    ("Entertainment", "Entertainment"),
                    ("Fuel", "Fuel"),
                    ("Education", "Education"),
                    ("Monthly Bills", "Monthly Bills"),
                    ("Miscellaneous", "Miscellaneous"),
                ],
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Food", "Food"),
                            ("Clothing", "Clothing"),
                            ("Entertainment", "Entertainment"),
                            ("Fuel", "Fuel"),
                            ("Education", "Education"),
                            ("Monthly Bills", "Monthly Bills"),
                            ("Miscellaneous", "Miscellaneous"),
                        ],
                        max_length=100,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
