# Generated by Django 5.0.6 on 2024-05-20 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance_tracker", "0003_alter_expense_date_alter_expense_tag_budget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="date",
            field=models.DateField(),
        ),
    ]
